name: CraftIRC
main: com.ensifera.animosity.craftirc.CraftIRC
version: 2.16
softdepend: [Vault]
commands:
  irc:
    description: Sends a message to all IRC channels
    usage: /<command> [msg]
  ircm:
    description: Send IRC message to tag (use command '/irctags' for listing)
    usage: /<command> [tag] [msg]
  ircw:
    description: PM an IRC user
    usage: /<command> [player] [msg]
  ircwho:
    description: Lists users in an IRC channel
    usage: /<command> [channel]
  admins!:
    description: Sends a notice to admins on IRC
    usage: /<command> [msg]
  ircraw:
    description: Sends a raw line to IRC
    usage: /<command> [botid] [rawirc]
  say:
    description: Broadcast a message to everyone, including IRC
    usage: /<command> [message]
